---
output: html_document
---

```{r setup, include=FALSE, warning=F}
knitr::opts_chunk$set(echo=FALSE, message=FALSE)
```

###  The World Consonant Alternation Database {.tabset .tabset-fade .tabset-pills}
Some characters may be displayed incorrectly.

Download database: [.tsv](https://raw.githubusercontent.com/agricolamz/wcad/master/database.csv)

#### about database
Here is a map of the languages from WCAD:
```{r}
bibliography <- read.csv("bibliography.csv", sep = "\t", na.strings = "")
wwsb <- read.csv("database.csv", sep = "\t", na.strings = "")
names(wwsb)[2:3] <- c("X→", "→Y")
library(lingtypology)
map.feature(unique(bibliography$language),
            label = unique(bibliography$language),
            label.hide = TRUE,
            color = "blue")
```

#### search
```{r}
library(DT)
wwsb$language <- url.lang(wwsb$language)
datatable(wwsb, filter = 'top', rownames = FALSE, options = list(pageLength = 20, dom = 'tip'), escape = FALSE)
```

#### bibliography
```{r}
bibliography$language <- url.lang(bibliography$language)
datatable(bibliography, filter = 'top', rownames = FALSE, options = list(pageLength = 20, autoWidth = FALSE), escape = FALSE)
```
