---
output: 
  html_document:
    include:
      after_body: footer.html
knit: (function(inputFile, encoding) { 
      out_dir <- 'docs';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'index.html')) })
---

```{r setup, include=FALSE, warning=F}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning = FALSE)
library(lingtypology)
library(tidyverse)
```

###  The World Consonant Alternation Database {.tabset .tabset-fade .tabset-pills}
Some characters may be displayed incorrectly.

Download database: [.tsv](https://raw.githubusercontent.com/agricolamz/wcad/master/database.csv)

#### about database
Here is a map of the languages from WCAD:
```{r}
bibliography <- read_tsv("bibliography.csv")
wwsb <- read_tsv("database.csv")

library(lingtypology)
wwsb %>% 
  distinct(glottocode, language) %>% 
  left_join(bibliography) %>% 
  mutate(language = lang.gltc(glottocode)) %>% 
  select(-glottocode) ->
  bibliography

map.feature(unique(bibliography$language),
            color = "blue")
```

#### search
```{r}
library(DT)
wwsb %>% 
  distinct(glottocode, language) %>% 
  left_join(bibliography) %>% 
  mutate(language = url.lang(language)) %>% 
  select(-glottocode) %>% 
  datatable(filter = 'top', rownames = FALSE, options = list(pageLength = 20, dom = 'tip'), escape = FALSE)
```

#### bibliography
```{r}
bibliography$language <- url.lang(bibliography$language)
datatable(bibliography, filter = 'top', rownames = FALSE, options = list(pageLength = 20, autoWidth = FALSE), escape = FALSE)
```
